
// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using MLModel1_ConsoleApp1;
using static MLModel1_ConsoleApp1.MLModel1;

// //Create single instance of sample data from first line of dataset for model input
//MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
//{
//    MaToHop = @"B00",
//    DiemToHop = 20.2F,
//    NhomTinhCach = @"Investigative",
//};



//Console.WriteLine("Using model to make single prediction -- Comparing actual NhomNganh with predicted NhomNganh from sample data...\n\n");


//Console.WriteLine($"MaToHop: {@"B00"}");
//Console.WriteLine($"DiemToHop: {20.2F}");
//Console.WriteLine($"NhomTinhCach: {@"Investigative"}");
//Console.WriteLine($"NhomNganh: {@"YDuoc_SucKhoe"}");


//var sortedScoresWithLabel = MLModel1.PredictAllLabels(sampleData);
//Console.WriteLine($"{"Class",-40}{"Score",-20}");
//Console.WriteLine($"{"-----",-40}{"-----",-20}");

//foreach (var score in sortedScoresWithLabel)
//{
//    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
//}

//Console.WriteLine("=============== End of process, hit any key to finish ===============");
//Console.ReadKey();

// 1. Khởi tạo ML Context
var mlContext = new MLContext();

string dataPath = @"C:\Users\Duy\Documents\MyProject\ml_dotnet_NLCS\TestML_NET\Data\dataset.csv";
// 2. Load lại tập dữ liệu 1000 dòng của bạn
IDataView trainData = mlContext.Data.LoadFromTextFile<ModelInput>(dataPath, hasHeader: true, separatorChar: ',');

// 3. Load mô hình đã được train xong bởi Model Builder
ITransformer trainedModel = mlContext.Model.Load("MLModel1.mlnet", out var modelInputSchema);

// 4. Chạy dự đoán trên toàn bộ tập dữ liệu để đánh giá
var predictions = trainedModel.Transform(trainData);
// Chỉ rõ cho hàm Evaluate biết: Cột chứa nhãn gốc là "NhomNganh" 
// và cột chứa kết quả dự đoán từ mô hình Model Builder xuất ra là "PredictedLabel"
var metrics = mlContext.MulticlassClassification.Evaluate(
    predictions,
    labelColumnName: "NhomNganh",
    scoreColumnName: "Score",
    predictedLabelColumnName: "PredictedLabel"
);

// Bây giờ bạn có thể in ma trận nhầm lẫn một cách an toàn
Console.WriteLine(metrics.ConfusionMatrix.GetFormattedConfusionTable());
