
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    MaToHop = @"A01",
    DiemToHop = 19.45F,
    NhomTinhCach = @"Enterprising",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual NhomNganh with predicted NhomNganh from sample data...\n\n");


Console.WriteLine($"MaToHop: {@"A01"}");
Console.WriteLine($"DiemToHop: {19.45F}");
Console.WriteLine($"NhomTinhCach: {@"Enterprising"}");
Console.WriteLine($"NhomNganh: {@"Luat_KinhTe"}");


var sortedScoresWithLabel = MLModel1.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

